-- ================================================================================= --
--                                                                                   --
--        NJILA COURIER APP - SUPABASE DATABASE SETUP SCRIPT                           --
--                                                                                   --
--  This script will create and configure all necessary tables, policies, and        --
--  triggers for the application.                                                    --
--                                                                                   --
--  Instructions:                                                                    --
--  1. Navigate to the "SQL Editor" in your Supabase project dashboard.              --
--  2. Click "+ New query".                                                          --
--  3. Copy and paste the ENTIRE content of this file into the editor.               --
--  4. Click "Run".                                                                  --
--                                                                                   --
--  This script is designed to be idempotent, meaning it can be run multiple         --
--  times without causing errors. It will safely create tables if they don't exist   --
--  and update policies.                                                             --
--                                                                                   --
-- ================================================================================= --


-- ================================================================================= --
--  SECTION 1: DRIVERS TABLE                                                         --
-- ================================================================================= --

-- Create the 'drivers' table if it doesn't already exist.
-- This table stores public profile information for each driver.
CREATE TABLE IF NOT EXISTS public.drivers (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  full_name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  vehicle_model TEXT,
  license_plate TEXT,
  insurance_verified BOOLEAN DEFAULT FALSE,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT
);
COMMENT ON TABLE public.drivers IS 'Stores public profile information for each user (driver).';
COMMENT ON COLUMN public.drivers.id IS 'Links to the auth.users table.';


-- Enable Row Level Security (RLS) on the 'drivers' table.
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to ensure a clean state before creating new ones.
DROP POLICY IF EXISTS "Drivers can view their own profile." ON public.drivers;
DROP POLICY IF EXISTS "Users can update their own profile." ON public.drivers;
DROP POLICY IF EXISTS "Users can insert their own profile." ON public.drivers;

-- POLICY 1: Allow drivers to view their own profile.
CREATE POLICY "Drivers can view their own profile."
ON public.drivers FOR SELECT
USING (auth.uid() = id);

-- POLICY 2: Allow drivers to update their own profile.
CREATE POLICY "Users can update their own profile."
ON public.drivers FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- POLICY 3: Allow users to insert their own profile.
CREATE POLICY "Users can insert their own profile."
ON public.drivers FOR INSERT
WITH CHECK (auth.uid() = id);


-- ================================================================================= --
--  SECTION 2: ORDERS TABLE                                                          --
-- ================================================================================= --

-- Create the 'orders' table if it doesn't already exist.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    title TEXT,
    distance TEXT,
    time TEXT,
    stops INTEGER,
    payout NUMERIC,
    currency TEXT,
    pickup_address TEXT,
    destination_address TEXT,
    status TEXT DEFAULT 'Pending',
    delivery_type TEXT,
    driver_id UUID REFERENCES public.drivers(id)
);
COMMENT ON TABLE public.orders IS 'Stores all delivery jobs.';
COMMENT ON COLUMN public.orders.driver_id IS 'Links to the driver who has accepted the order.';


-- Safely add the 'driver_id' column if it doesn't exist, for backwards compatibility.
DO $$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='driver_id') THEN
    ALTER TABLE public.orders ADD COLUMN driver_id UUID REFERENCES public.drivers(id);
  END IF;
END $$;


-- Enable Row Level Security (RLS) on the 'orders' table.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to ensure a clean state before creating new ones.
DROP POLICY IF EXISTS "Drivers can view available or their own jobs" ON public.orders;
DROP POLICY IF EXISTS "Authenticated users can view available jobs" ON public.orders;
DROP POLICY IF EXISTS "Drivers can view their own jobs" ON public.orders;
DROP POLICY IF EXISTS "Drivers can accept or update their own jobs" ON public.orders;


-- POLICY 1: Allow users to see available jobs, or jobs assigned to them.
-- This single SELECT policy is simpler and more reliable. It allows any authenticated
-- user to see jobs that are 'Pending' and of 'courier' type, OR any job that is
-- assigned to them via their driver_id.
CREATE POLICY "Drivers can view available or their own jobs"
ON public.orders FOR SELECT
USING (
  (status = 'Pending' AND delivery_type = 'courier') OR (auth.uid() = driver_id)
);


-- POLICY 2: Allow drivers to accept a new job or update a job they've accepted.
-- USING clause: This policy applies to rows where the driver_id is the current user OR is NULL (an unassigned job).
-- WITH CHECK clause: Ensures that any update can only set the driver_id to the current user's ID.
CREATE POLICY "Drivers can accept or update their own jobs"
ON public.orders FOR UPDATE
USING (
  auth.uid() = driver_id OR driver_id IS NULL
)
WITH CHECK (
  auth.uid() = driver_id
);


-- ================================================================================= --
--  SECTION 3: AUTOMATIC DRIVER CREATION                                             --
-- ================================================================================= --

-- Create a function that automatically inserts a new row into public.drivers
-- whenever a new user signs up in auth.users.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.drivers (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create a trigger that executes the handle_new_user function after a new user is created.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ================================================================================= --
--                      END OF SCRIPT                                                --
-- ================================================================================= --
