-- Supabase Setup Script for Njila Delivery App
-- Version: 1.4
--
-- This script is designed to be idempotent and non-destructive.
-- You can run it multiple times without causing errors or data loss.
-- It will create tables and policies only if they do not already exist.
--
-- Steps to run:
-- 1. Navigate to the "SQL Editor" in your Supabase project dashboard.
-- 2. Click "+ New query".
-- 3. Copy and paste the entire content of this file into the editor.
-- 4. Click "Run".

-- 1. Create the 'drivers' table if it doesn't exist.
CREATE TABLE IF NOT EXISTS public.drivers (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  full_name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  vehicle_model TEXT,
  license_plate TEXT,
  insurance_verified BOOLEAN DEFAULT FALSE,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT
);

-- Add comments for clarity.
COMMENT ON TABLE public.drivers IS 'Stores public profile information for each user (driver).';
COMMENT ON COLUMN public.drivers.id IS 'Links to the auth.users table.';

-- 2. Enable Row Level Security (RLS) on the 'drivers' table.
-- This is a crucial security step. It is safe to run this multiple times.
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;

-- 3. Create policies for the 'drivers' table.
-- These policies control who can access or modify data.
-- Each 'CREATE POLICY' includes 'IF NOT EXISTS' to prevent errors on re-runs.

-- Policy: Allow drivers to view their own profile.
CREATE POLICY "Drivers can view their own profile."
ON public.drivers FOR SELECT
USING (auth.uid() = id);

-- Policy: Allow drivers to update their own profile.
CREATE POLICY "Drivers can update their own profile."
ON public.drivers FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- **** NEW POLICY TO FIX REGISTRATION ERROR ****
-- Policy: Allow users to create their own driver profile.
CREATE POLICY "Drivers can create their own profile."
ON public.drivers FOR INSERT
WITH CHECK (auth.uid() = id);

-- 4. Create the 'orders' table if it doesn't exist.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT,
    distance TEXT,
    time TEXT,
    stops INTEGER,
    payout NUMERIC,
    currency TEXT,
    pickup_address TEXT,
    status TEXT DEFAULT 'Pending',
    delivery_type TEXT,
    -- This column links an order to a driver.
    driver_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Add a non-destructive command to add the driver_id column if it's missing.
-- This is useful for migrating older table versions.
DO $$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='driver_id') THEN
    ALTER TABLE public.orders ADD COLUMN driver_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
  END IF;
END $$;


-- Add comments for clarity.
COMMENT ON TABLE public.orders IS 'Stores all delivery jobs available in the system.';
COMMENT ON COLUMN public.orders.driver_id IS 'The driver who has accepted the order.';

-- 5. Enable Row Level Security (RLS) on the 'orders' table.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 6. Create policies for the 'orders' table.

-- Policy: Allow any authenticated user (driver) to see 'Pending' courier jobs.
CREATE POLICY "Drivers can view available courier jobs."
ON public.orders FOR SELECT
USING (
  auth.role() = 'authenticated' AND
  status = 'Pending' AND
  delivery_type = 'courier'
);

-- Policy: Allow a driver to see an order they have accepted.
CREATE POLICY "Drivers can view their assigned jobs."
ON public.orders FOR SELECT
USING (auth.uid() = driver_id);

-- Policy: Allow a driver to accept a 'Pending' job by updating its status and assigning it to themselves.
-- They can only do this if no other driver has taken it yet (driver_id is NULL).
CREATE POLICY "Drivers can accept available jobs."
ON public.orders FOR UPDATE
USING (
  auth.uid() = driver_id OR -- Allows future updates by the assigned driver
  (status = 'Pending' AND driver_id IS NULL)
)
WITH CHECK (
  -- When accepting, the new driver_id must be the current user's ID.
  driver_id = auth.uid()
);

-- 7. Create a function to automatically create a profile when a new user signs up.
-- This function is triggered when a new entry is added to 'auth.users'.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Check if a profile for the new user already exists.
  IF NOT EXISTS (SELECT 1 FROM public.drivers WHERE id = new.id) THEN
    INSERT INTO public.drivers (id, email, full_name)
    VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. Create a trigger to execute the function after a new user is created.
-- We drop the trigger first to ensure this script can be re-run without errors.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 9. Optional: Storage Policies (if using for avatars).
-- These are included for completeness.
-- Make sure a bucket named 'avatars' exists in Supabase Storage.

-- Drop existing policies to avoid conflicts on re-run
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
DROP POLICY IF EXISTS "Anyone can upload an avatar." ON storage.objects;
DROP POLICY IF EXISTS "Anyone can update their own avatar." ON storage.objects;

-- Create policies for viewing, uploading, and updating avatars.
CREATE POLICY "Avatar images are publicly accessible."
ON storage.objects FOR SELECT
USING ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can upload an avatar."
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can update their own avatar."
ON storage.objects FOR UPDATE
USING ( auth.uid() = owner )
WITH CHECK ( bucket_id = 'avatars' );
