-- This script sets up the necessary tables and Row Level Security (RLS) policies
-- for the Njila driver app. It is designed to be idempotent, meaning you can
-- run it multiple times without causing errors.
--
-- Steps to run:
-- 1. Navigate to the "SQL Editor" in your Supabase project dashboard.
-- 2. Click "+ New query".
-- 3. Copy and paste the entire content of this file into the editor.
-- 4. Click "Run".

-- 1. Create the 'drivers' table if it doesn't exist.
-- This table stores public profile information for each user (driver).
CREATE TABLE IF NOT EXISTS public.drivers (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  full_name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  vehicle_model TEXT,
  license_plate TEXT,
  insurance_verified BOOLEAN DEFAULT FALSE,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT
);
COMMENT ON TABLE public.drivers IS 'Stores public profile information for each user (driver).';
COMMENT ON COLUMN public.drivers.id IS 'Links to the auth.users table.';

-- 2. Create the 'orders' table if it doesn't exist.
-- This table stores information about delivery orders.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT,
    distance TEXT,
    time TEXT,
    stops INTEGER,
    payout NUMERIC,
    currency TEXT,
    pickup_address TEXT,
    destination_address TEXT,
    status TEXT DEFAULT 'Pending',
    delivery_type TEXT,
    driver_id UUID REFERENCES public.drivers(id)
);
COMMENT ON TABLE public.orders IS 'Stores delivery order details.';

-- Add driver_id column if it doesn't exist (for backward compatibility)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM   information_schema.columns
        WHERE  table_schema = 'public'
        AND    table_name = 'orders'
        AND    column_name = 'driver_id'
    ) THEN
        ALTER TABLE public.orders ADD COLUMN driver_id UUID REFERENCES public.drivers(id);
        COMMENT ON COLUMN public.orders.driver_id IS 'Foreign key linking to the driver assigned to the order.';
    END IF;
END $$;


-- 3. Set up Row Level Security (RLS).
-- This is a crucial security step.

-- RLS for 'drivers' table
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Drivers can view their own profile." ON public.drivers;
CREATE POLICY "Drivers can view their own profile."
ON public.drivers FOR SELECT
USING (auth.uid() = id);

DROP POLICY IF EXISTS "Drivers can update their own profile." ON public.drivers;
CREATE POLICY "Drivers can update their own profile."
ON public.drivers FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can create their own driver profile." ON public.drivers;
CREATE POLICY "Users can create their own driver profile."
ON public.drivers FOR INSERT
WITH CHECK (auth.uid() = id);

-- RLS for 'orders' table
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Drivers can view available or their assigned orders." ON public.orders;
CREATE POLICY "Drivers can view available or their assigned orders."
ON public.orders FOR SELECT
USING (
  (status = 'Confirmed' AND delivery_type = 'courier') OR
  (driver_id = auth.uid())
);

DROP POLICY IF EXISTS "Drivers can update status of their assigned orders." ON public.orders;
CREATE POLICY "Drivers can update status of their assigned orders."
ON public.orders FOR UPDATE
USING (driver_id = auth.uid())
WITH CHECK (driver_id = auth.uid());


-- 4. Create a function to automatically create a profile when a new user signs up.
-- This is connected to a trigger on the auth.users table.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.drivers (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Create a trigger to execute the function after a new user is created.
-- This ensures every new user gets a profile entry.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. Set up RLS for Supabase storage (if used for avatars).
-- Make sure to create a bucket named 'avatars'.
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
CREATE POLICY "Avatar images are publicly accessible."
ON storage.objects FOR SELECT
USING ( bucket_id = 'avatars' );

DROP POLICY IF EXISTS "Anyone can upload an avatar." ON storage.objects;
CREATE POLICY "Anyone can upload an avatar."
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'avatars' );

DROP POLICY IF EXISTS "Anyone can update their own avatar." ON storage.objects;
CREATE POLICY "Anyone can update their own avatar."
ON storage.objects FOR UPDATE
USING ( auth.uid() = owner )
WITH CHECK ( bucket_id = 'avatars' );
